name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # se ejecuta al hacer push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4

      # 2. Publicar la carpeta `site`
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site